# Generated by Django 5.1.6 on 2025-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('I&C', 'Information & Computing'), ('E&T', 'Engineering & Technology'), ('I&R', 'Interdisciplinary and Research'), ('LS', 'Life Sciences'), ('LAMS', 'Liberal Arts & Media Studies'), ('MS', 'Management Studies'), ('SC', 'Sciences'), ('CCSD', 'CCSD')], max_length=4)),
            ],
            options={
                'unique_together': {('name', 'faculty')},
            },
        ),
    ]
