# Generated by Django 5.1.6 on 2025-02-27 07:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE_CODE', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('COURSE_NAME', models.CharField(max_length=200)),
                ('CATEGORY', models.CharField(choices=[('CREDITS', 'Credits'), ('CBCS', 'CBCS')], max_length=7)),
                ('COURSE_CATEGORY', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('ELECTIVE', 'Elective')], max_length=10)),
                ('TYPE', models.CharField(choices=[('DISSERTATION', 'Dissertation'), ('LABORATORY', 'Laboratory'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project'), ('THEORY', 'Theory'), ('THEORY AND PRACTICAL', 'Theory and Practical'), ('TUTORIAL', 'Tutorial')], max_length=20)),
                ('CREDIT_SCHEME', models.CharField(choices=[('CREDIT', 'Credit'), ('CBCS', 'CBCS'), ('NEP', 'NEP')], max_length=6)),
                ('CBCS_CATEGORY', models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Minor'), ('CORE', 'Core'), ('DSE', 'DSE'), ('GE', 'GE'), ('OE', 'OE'), ('VAC', 'VAC'), ('AECC', 'AECC'), ('SEC', 'SEC'), ('MDC', 'MDC'), ('IDC', 'IDC')], max_length=6)),
                ('MAXIMUM_CREDIT', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('QUALIFYING_IN_NATURE', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3)),
                ('DISCIPLINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.department')),
            ],
        ),
    ]
